version: '3.8'
services:
  # Infrastructure Services
  nginx:
    image: nginx:1.25.1
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-dev.conf:/etc/nginx/nginx.conf
  postgres:
    image: postgres:15.1
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=argus
      - POSTGRES_PASSWORD=changeme
  # Application Services
  argus-auth:
    build:
      context: ../argus-auth-services
      dockerfile: ../argus-auth-services/src/main/docker/Dockerfile.jvm
    image: zygon/argus-auth-services
    container_name: argus-auth
    volumes:
      - ./public.pem:/etc/jwt/public.pem
      - ./private.pem:/etc/jwt/private.pem
    environment:
      - QUARKUS_HTTP_PORT=80
      - QUARKUS_REST_CLIENT_ARGUS_GROUPS_API_URL=http://argus-groups
      - ARGUS_AUTH_PUBLIC_KEY=/etc/jwt/public.pem
      - ARGUS_AUTH_PRIVATE_KEY=/etc/jwt/private.pem
      - ARGUS_AUTH_ISSUER=http://localhost/auth
  argus-groups:
    build:
      context: ../argus-group-services
      dockerfile: ../argus-group-services/src/main/docker/Dockerfile.jvm
    image: zygon/argus-group-services
    container_name: argus-groups
    environment:
      - QUARKUS_HTTP_PORT=80
      - ARGUS_AUTH_PUBLIC_KEY=http://argus-auth/auth/key
      - ARGUS_AUTH_ISSUER=http://localhost/auth
      - ARGUS_GROUP_MAX_OWNED_GROUPS=3
      - ARGUS_GROUP_JOOQ_DIALECT=POSTGRES
      - QUARKUS_DATASOURCE_DB_KIND=postgresql
      - QUARKUS_DATASOURCE_REACTIVE_URL=postgresql://postgres:5432/argus?search_path=argus
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://postgres:5432/argus?search_path=argus
      - QUARKUS_DATASOURCE_USERNAME=argus
      - QUARKUS_DATASOURCE_PASSWORD=changeme
      - QUARKUS_FLYWAY_DEFAULT_SCHEMA=argus
  argus-locations:
    build:
      context: ../argus-location-services
      dockerfile: ../argus-location-services/src/main/docker/Dockerfile.jvm
    image: zygon/argus-location-services
    container_name: argus-locations
    environment:
      - QUARKUS_HTTP_PORT=80
      - ARGUS_AUTH_PUBLIC_KEY=http://argus-auth/auth/key
      - ARGUS_AUTH_ISSUER=http://localhost/auth
